version: '3'

services:
  site:
    image: wordpress:latest
    container_name: wp_site
    restart: always
    depends_on:
      - database
    ports:
      - "127.0.0.1:7080:80"
    environment:
      WORDPRESS_DB_HOST: database
      WORDPRESS_DB_USER: ${DBUSER}
      WORDPRESS_DB_PASSWORD: ${DBPASS}
      WORDPRESS_DB_NAME: ${DBNAME}
    volumes:
      - content:/var/www/html/wp-content
    networks:
      WPNet:
        ipv4_address: 10.0.0.2

  database:
    image: mysql:5.7
    container_name: wp_db
    restart: always
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 1
      MYSQL_USER: ${DBUSER}
      MYSQL_PASSWORD: ${DBPASS}
      MYSQL_DATABASE: ${DBNAME}
    volumes:
      - database:/var/lib/mysql
    working_dir: /var/lib/mysql
    networks:
      WPNet:
        ipv4_address: 10.0.0.3

volumes:
  content:
  database:

networks:
  WPNet:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "10.0.0.0/29"

